[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_SKIP_DEPENDENCY_CACHE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["lib/generated/prisma/**"] 