[build]
  command = "node scripts/migrate-db.js && pnpm install && pnpm build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  USE_PNPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["lib/generated/prisma/**"] 