[build]
  command = "pnpm install && pnpm build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  USE_PNPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/netlify-plugin-prisma-provider"

[functions]
  included_files = ["lib/generated/prisma/**"] 