[build]
  command = "npx pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["lib/generated/prisma/**"] 