name: Deploy Backend to Cloud Run
on:
  push:
    branches: [main, preview]
    paths:
      - 'api/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/$PROJECT_ID/api:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/api:${{ github.sha }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy api \
            --image gcr.io/$PROJECT_ID/api:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy to Preview
        if: github.ref == 'refs/heads/preview'
        run: |
          gcloud run deploy preview \
            --image gcr.io/$PROJECT_ID/api:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated 