name: Netlify Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      # Trigger Netlify build
      - name: Trigger Netlify build
        run: netlify build --trigger --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} 