name: Netlify Build & Deploy

on:
  push:
    branches: 
      - main
      - preview
  pull_request:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      # Trigger Netlify build and deploy
      - name: Trigger Netlify build and deploy
        run: netlify deploy --trigger --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }} 